# Rafael TCC - Projeto 04

Análise de consitência dos dados de touros Nelore presentes na plataforma CRV, segundo o programa de melhoramento

## Bibliotecas

In [1]:
import os
import pandas as pd

print("Bibliotecas carregadas com sucesso!")

Bibliotecas carregadas com sucesso!

## Extração, leitura e transformação dos dados

### Leitura dos dados

In [2]:
# Leitura do arquivo de dados
programa = 'ANCP'
df = pd.read_csv(f'Dados/CSV/NeloreCRV_{programa}.csv')

### Verificação da existência de observações duplicadas

In [3]:
# Verificando se a observações duplicadas
duplicados = df.duplicated().sum()
print(f"Linhas duplicadas no dataset: {duplicados}")

# Se houver uma chave única (ex: 'crv_code' ou 'rgd'):
print(f"Códigos duplicados: {df['crv_code'].duplicated().sum()}")

Linhas duplicadas no dataset: 0
Códigos duplicados: 0

### Verificação preliminar dos dados

In [4]:
# Verificação preliminar dos dados (nomes das variáveis, tipo de dado e a existência de valores nulos)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 63 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   crv_code            118 non-null    int64
 1   nome_oficial        118 non-null    str
 2   raca                118 non-null    str
 3   rgd                 118 non-null    str
 4   data_nascimento     118 non-null    str
 5   preco_convencional  118 non-null    float64
 6   selos               118 non-null    str
 7   ANCP_N°_REBANHOS    118 non-null    float64
 8   ANCP_N°_FILHOS      118 non-null    float64
 9   ANCP_DFPP_DEP       118 non-null    float64
 10  ANCP_DFPP_ACC       118 non-null    float64
 11  ANCP_DFPP_TOP       118 non-null    float64
 12  ANCP_PN_DEP         118 non-null    float64
 13  ANCP_PN_ACC         118 non-null    float64
 14  ANCP_PN_TOP         118 non-null    float64
 15  ANCP_DP210_DEP      118 non-null    float64
 16  ANCP_DP210_ACC      118 non-null    float64
 17  ANCP_DP210_TOP      118 non-null    float64
 18  ANCP_DP365_DEP      118 non-null    float64
 19  ANCP_DP365_ACC      118 non-null    float64
 20  ANCP_DP365_TOP      118 non-null    float64
 21  ANCP_DP450_DEP      118 non-null    float64
 22  ANCP_DP450_ACC      118 non-null    float64
 23  ANCP_DP450_TOP      118 non-null    float64
 24  ANCP_DCAR_DEP       118 non-null    float64
 25  ANCP_DCAR_ACC       118 non-null    float64
 26  ANCP_DCAR_TOP       118 non-null    float64
 27  ANCP_MP120_DEP      118 non-null    float64
 28  ANCP_MP120_ACC      118 non-null    float64
 29  ANCP_MP120_TOP      118 non-null    float64
 30  ANCP_MP210_DEP      118 non-null    float64
 31  ANCP_MP210_ACC      118 non-null    float64
 32  ANCP_MP210_TOP      118 non-null    float64
 33  ANCP_PAC_DEP        118 non-null    float64
 34  ANCP_PAC_ACC        118 non-null    float64
 35  ANCP_PAC_TOP        118 non-null    float64
 36  ANCP_D3P_DEP        118 non-null    float64
 37  ANCP_D3P_ACC        118 non-null    float64
 38  ANCP_D3P_TOP        118 non-null    float64
 39  ANCP_DIPP_DEP       118 non-null    float64
 40  ANCP_DIPP_ACC       118 non-null    float64
 41  ANCP_DIPP_TOP       118 non-null    float64
 42  ANCP_DPE450_DEP     118 non-null    float64
 43  ANCP_DPE450_ACC     118 non-null    float64
 44  ANCP_DPE450_TOP     118 non-null    float64
 45  ANCP_DSTAY_DEP      118 non-null    float64
 46  ANCP_DSTAY_ACC      118 non-null    float64
 47  ANCP_DSTAY_TOP      118 non-null    float64
 48  ANCP_DAOL_DEP       118 non-null    float64
 49  ANCP_DAOL_ACC       118 non-null    float64
 50  ANCP_DAOL_TOP       118 non-null    float64
 51  ANCP_DACAB_DEP      118 non-null    float64
 52  ANCP_DACAB_ACC      118 non-null    float64
 53  ANCP_DACAB_TOP      118 non-null    float64
 54  ANCP_DMARM_DEP      118 non-null    float64
 55  ANCP_DMARM_ACC      118 non-null    float64
 56  ANCP_DMARM_TOP      118 non-null    float64
 57  ANCP_DFRAME_DEP     118 non-null    float64
 58  ANCP_DFRAME_ACC     118 non-null    float64
 59  ANCP_DFRAME_TOP     118 non-null    float64
 60  ANCP_MGTe_DEP       118 non-null    float64
 61  ANCP_MGTe_ACC       118 non-null    float64
 62  ANCP_MGTe_TOP       118 non-null    float64
dtypes: float64(57), int64(1), str(5)
memory usage: 58.2 KB

### Renomeação das variáveis (colunas)

In [5]:
# Simplificacão e alteração dos nomes das variáveis de registro e semem para caixa alta 
novos_nomes = {
    'crv_code': 'CRV_COD',
    'nome_oficial': 'NOME',
    'raca': 'RACA',
    'rgd': 'RGD',
    'data_nascimento': 'DNASC',
    'preco_convencional': 'SEMEM',
    'selos': 'SELOS'
}

df.rename(columns=novos_nomes, inplace=True)

In [6]:
# Removendo o prefixo ANCP e ANCP_D das variáveis relacionadas a avalição genética dos animais
df.columns = [c.replace('ANCP_D', '') for c in df.columns]
df.columns = [c.replace('ANCP_', '') for c in df.columns]

In [7]:
# Verificação preliminar das dimensões dos dados
print(f"Dimensões do dataset: {df.shape[0]} touros x {df.shape[1]} variáveis")

Dimensões do dataset: 118 touros x 63 variáveis

In [8]:
# Eliminação das observações cuja variável SEMEM apresentaram valor nulo
df_notnull = df[df['SEMEM'].notna()]

print(f"Dimensões do dataset: {df_notnull.shape[0]} touros x {df_notnull.shape[1]} variáveis")

Dimensões do dataset: 118 touros x 63 variáveis

In [9]:
# Verificação dos dados após as alterações nos nomes das variáveis e eliminação dos valores nulos na variável SEMEM
df_notnull.info()

<class 'pandas.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 63 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CRV_COD      118 non-null    int64
 1   NOME         118 non-null    str
 2   RACA         118 non-null    str
 3   RGD          118 non-null    str
 4   DNASC        118 non-null    str
 5   SEMEM        118 non-null    float64
 6   SELOS        118 non-null    str
 7   N°_REBANHOS  118 non-null    float64
 8   N°_FILHOS    118 non-null    float64
 9   FPP_DEP      118 non-null    float64
 10  FPP_ACC      118 non-null    float64
 11  FPP_TOP      118 non-null    float64
 12  PN_DEP       118 non-null    float64
 13  PN_ACC       118 non-null    float64
 14  PN_TOP       118 non-null    float64
 15  P210_DEP     118 non-null    float64
 16  P210_ACC     118 non-null    float64
 17  P210_TOP     118 non-null    float64
 18  P365_DEP     118 non-null    float64
 19  P365_ACC     118 non-null    float64
 20  P365_TOP     118 non-null    float64
 21  P450_DEP     118 non-null    float64
 22  P450_ACC     118 non-null    float64
 23  P450_TOP     118 non-null    float64
 24  CAR_DEP      118 non-null    float64
 25  CAR_ACC      118 non-null    float64
 26  CAR_TOP      118 non-null    float64
 27  MP120_DEP    118 non-null    float64
 28  MP120_ACC    118 non-null    float64
 29  MP120_TOP    118 non-null    float64
 30  MP210_DEP    118 non-null    float64
 31  MP210_ACC    118 non-null    float64
 32  MP210_TOP    118 non-null    float64
 33  PAC_DEP      118 non-null    float64
 34  PAC_ACC      118 non-null    float64
 35  PAC_TOP      118 non-null    float64
 36  3P_DEP       118 non-null    float64
 37  3P_ACC       118 non-null    float64
 38  3P_TOP       118 non-null    float64
 39  IPP_DEP      118 non-null    float64
 40  IPP_ACC      118 non-null    float64
 41  IPP_TOP      118 non-null    float64
 42  PE450_DEP    118 non-null    float64
 43  PE450_ACC    118 non-null    float64
 44  PE450_TOP    118 non-null    float64
 45  STAY_DEP     118 non-null    float64
 46  STAY_ACC     118 non-null    float64
 47  STAY_TOP     118 non-null    float64
 48  AOL_DEP      118 non-null    float64
 49  AOL_ACC      118 non-null    float64
 50  AOL_TOP      118 non-null    float64
 51  ACAB_DEP     118 non-null    float64
 52  ACAB_ACC     118 non-null    float64
 53  ACAB_TOP     118 non-null    float64
 54  MARM_DEP     118 non-null    float64
 55  MARM_ACC     118 non-null    float64
 56  MARM_TOP     118 non-null    float64
 57  FRAME_DEP    118 non-null    float64
 58  FRAME_ACC    118 non-null    float64
 59  FRAME_TOP    118 non-null    float64
 60  MGTe_DEP     118 non-null    float64
 61  MGTe_ACC     118 non-null    float64
 62  MGTe_TOP     118 non-null    float64
dtypes: float64(57), int64(1), str(5)
memory usage: 58.2 KB

### Avaliando a distribuição de valores da variável SEMEM

In [10]:

df_cols = df_notnull.columns[df_notnull.columns.isin(['SEMEM'])]

# Passa a lista inteira de colunas, aplica o describe com os percentis e transpõe (.T)
df_resumo_SEMEM = (
    df[df_cols]
    .describe(percentiles=[0.05, 0.25, 0.50, 0.75, 0.90, 0.95])
    .T
    .round(2)
)

display(df_resumo_SEMEM)

       count  mean    std  min     5%   25%   50%   75%   90%    95%    max
SEMEM  118.0  38.9  44.16  0.0  21.42  31.2  31.2  33.9  38.9  49.05  346.5

In [11]:
# Eliminação dos preços inválidos (<= 0) e dos valores extremos (> R$ 100)
# Revisão v8 (out/2026): dos 4 touros removidos, só um tem preço inválido (R$ 0,00); os outros três (R$ 209,00, R$ 343,90 e
#   R$ 346,50) são valores extremos de touros de elite, fora da faixa dos demais (máximo de R$ 60,00). O artigo
#   passa a chamá-los de valores extremos e a justificar a exclusão.
df_valid = df_notnull[(df_notnull['SEMEM'] > 0) & (df_notnull['SEMEM'] <= 100 )].copy()

# Informações dos dados após processo de consistência
print(f"Touros originais com preço: {len(df_notnull)}")
print(f"Touros após remoção de outliers: {len(df_valid)} (removidas {len(df_notnull) - len(df_valid)} observações)")
print(f"Touros com preço convencional válido: {len(df_valid)} ({len(df_valid)/len(df)*100:.1f}% dos touros com avaliação ANCP)")
display(df_notnull.loc[~df_notnull.index.isin(df_valid.index), ['NOME', 'SEMEM']])

Touros originais com preço: 118
Touros após remoção de outliers: 114 (removidas 4 observações)
Touros com preço convencional válido: 114 (96.6% dos touros com avaliação ANCP)

                  NOME  SEMEM
40            KOCHI KA  343.9
47      MISTERIO  CASS  209.0
103  VITORIOSO SL NOVO  346.5
117   C1656 FIV DA EAO    0.0

In [12]:
# Revisão v9 (out/2026): exclusão dos touros da variedade Nelore Pintado, voltada a um nicho de mercado distinto.
# Revisão v11 (out/2026): com a base bruta do orientador (ver notebook 02), os dois touros Nelore Pintado avaliados pela
#   ANCP são excluídos aqui. O B6834 DA EAO, que antes era retirado pelo RGD, não consta dessa base.
excluidos = df_valid['RACA'] == 'Nelore Pintado'
display(df_valid.loc[excluidos, ['NOME', 'RACA', 'SEMEM']])
df_valid = df_valid[~excluidos].copy()
print(f"Touros na base final: {len(df_valid)}")

# Revisão v11 (out/2026): ordena a base pelo código CRV. O Random Forest e as partições da validação cruzada usam
#   semente fixa (random_state = 42), mas o sorteio depende da ordem das linhas; com a base do orientador, que vem em
#   outra ordem, os mesmos 113 touros davam importâncias e R² de validação um pouco diferentes. Com a ordenação, o
#   resultado não depende mais da ordem do arquivo de origem.
df_valid = df_valid.sort_values('CRV_COD').reset_index(drop=True)

                NOME            RACA  SEMEM
34  ILHEUS  GC DA SL  Nelore Pintado   43.7

Touros na base final: 113

In [13]:
df_cols = df_notnull.columns[df_notnull.columns.isin(['SEMEM'])]

# Passa a lista inteira de colunas, aplica o describe com os percentis e transpõe (.T)
df_resumo_SEMEM = (
    # Revisão (out/2026): esta tabela fica DEPOIS da limpeza, mas resumia `df` (base bruta, antes do filtro de preço).
    #   Passa a usar `df_valid`, a base usada em todas as análises (113 touros a partir da revisão v9).
    df_valid[df_cols]
    .describe(percentiles=[0.05, 0.25, 0.50, 0.75, 0.90, 0.95])
    .T
    .round(2)
)

display(df_resumo_SEMEM)

# Revisão v9 (out/2026): coeficiente de variação citado no artigo (Tabela 1).
print(f"CV do preço: {df_valid['SEMEM'].std() / df_valid['SEMEM'].mean() * 100:.2f}%")

       count   mean   std   min    5%   25%   50%   75%    90%   95%   max
SEMEM  113.0  32.28  6.76  18.7  21.9  31.2  31.2  33.9  38.42  45.4  60.0

CV do preço: 20.94%

### Exportação dos dados válidos para o arquivo NeloreCRV_ancp_validos.csv

In [14]:
df_valid.to_csv(f'Dados/CSV/NeloreCRV_{programa}_valido.csv', index=False)

print(f'Arquivo salvo com sucesso!!')

Arquivo salvo com sucesso!!